-- Base de datos FarmaGO
-- Sistema Digital Farmacia Italica
-- UCB San Pablo 2026
-- Modelo normalizado en BCNF — 11 tablas

CREATE DATABASE IF NOT EXISTS farmago;
USE farmago;

CREATE TABLE USUARIO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    direccion VARCHAR(255),
    telefono VARCHAR(20),
    rol ENUM('CLIENTE','REPARTIDOR','ADMINISTRADOR','CAJERO') NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE PROVEEDOR (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    contacto VARCHAR(100),
    telefono VARCHAR(20),
    email VARCHAR(150)
);

CREATE TABLE PRODUCTO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    precio DECIMAL(10,2) NOT NULL,
    imagen_url VARCHAR(500),
    categoria ENUM('OTC','ETICO') NOT NULL,
    stock_minimo INT DEFAULT 5,
    stock_actual INT DEFAULT 0,
    laboratorio_id INT,
    FOREIGN KEY (laboratorio_id) REFERENCES PROVEEDOR(id) ON DELETE RESTRICT
);

CREATE TABLE LOTE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    producto_id INT NOT NULL,
    cantidad INT NOT NULL,
    costo_unitario DECIMAL(10,2) NOT NULL,
    fecha_entrada DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    estado ENUM('DISPONIBLE','AGOTADO','VENCIDO','DEVUELTO') DEFAULT 'DISPONIBLE',
    FOREIGN KEY (producto_id) REFERENCES PRODUCTO(id) ON DELETE RESTRICT
);

CREATE TABLE PEDIDO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cliente_id INT NOT NULL,
    repartidor_id INT,
    total DECIMAL(10,2) NOT NULL,
    estado ENUM('PENDIENTE','CONFIRMADO','EN_CAMINO','ENTREGADO','CANCELADO','FALLIDO') DEFAULT 'PENDIENTE',
    tipo_entrega ENUM('DOMICILIO','PRESENCIAL') NOT NULL,
    metodo_pago ENUM('EFECTIVO','QR','AMBOS') NOT NULL,
    costo_envio DECIMAL(10,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (cliente_id) REFERENCES USUARIO(id) ON DELETE RESTRICT,
    FOREIGN KEY (repartidor_id) REFERENCES USUARIO(id) ON DELETE RESTRICT
);

CREATE TABLE DETALLE_PEDIDO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pedido_id INT NOT NULL,
    producto_id INT NOT NULL,
    cantidad INT NOT NULL,
    precio_unitario DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (pedido_id) REFERENCES PEDIDO(id) ON DELETE CASCADE,
    FOREIGN KEY (producto_id) REFERENCES PRODUCTO(id) ON DELETE RESTRICT
);

CREATE TABLE ENTREGA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pedido_id INT NOT NULL UNIQUE,
    repartidor_id INT NOT NULL,
    estado ENUM('ASIGNADO','EN_CAMINO','ENTREGADO','FALLIDO','REPROGRAMADO') DEFAULT 'ASIGNADO',
    observacion TEXT,
    fecha_entrega TIMESTAMP,
    entrega_exitosa BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (pedido_id) REFERENCES PEDIDO(id) ON DELETE RESTRICT,
    FOREIGN KEY (repartidor_id) REFERENCES USUARIO(id) ON DELETE RESTRICT
);

CREATE TABLE ALERTA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('STOCK_MINIMO','VENCIMIENTO_6M','VENCIMIENTO_4M','VENCIMIENTO_2M','ENTREGA_FALLIDA') NOT NULL,
    producto_id INT,
    lote_id INT,
    mensaje TEXT NOT NULL,
    leida BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (producto_id) REFERENCES PRODUCTO(id) ON DELETE RESTRICT,
    FOREIGN KEY (lote_id) REFERENCES LOTE(id) ON DELETE RESTRICT
);

CREATE TABLE CAJA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cajero_id INT NOT NULL,
    total_efectivo DECIMAL(10,2) DEFAULT 0,
    total_qr DECIMAL(10,2) DEFAULT 0,
    fecha DATE NOT NULL,
    turno ENUM('MANANA','TARDE','NOCHE','DIA_COMPLETO') NOT NULL,
    cerrado BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (cajero_id) REFERENCES USUARIO(id) ON DELETE RESTRICT
);

CREATE TABLE ACUERDO_COMERCIAL (
    id INT AUTO_INCREMENT PRIMARY KEY,
    proveedor_id INT NOT NULL,
    producto_id INT NOT NULL,
    UNIQUE KEY uk_acuerdo (proveedor_id, producto_id),
    FOREIGN KEY (proveedor_id) REFERENCES PROVEEDOR(id) ON DELETE RESTRICT,
    FOREIGN KEY (producto_id) REFERENCES PRODUCTO(id) ON DELETE RESTRICT
);

CREATE TABLE DESCUENTO (
    id INT AUTO_INCREMENT PRIMARY KEY,
    acuerdo_id INT NOT NULL,
    porcentaje DECIMAL(5,2) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (acuerdo_id) REFERENCES ACUERDO_COMERCIAL(id) ON DELETE RESTRICT
);
