# Configuracion de base de datos
spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:29293/railway
spring.datasource.username=root
spring.datasource.password=EQHZrooNEWmybTzCzHsADRbwmPTWKSWZ
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Puerto del servidor
server.port=8080
# Nombre de la aplicacion
spring.application.name=FarmaGO
spring.datasource.hikari.read-only=false
springdoc.swagger-ui.enabled=false
springdoc.scalar.enabled=true
springdoc.scalar.path=/scalar